export { NativeReductionError, nativeMapIRToSourceScopedIR, reduceNative, reduceNativeMapIR, reduceNativeSourceIR } from './reducer';
export type {
  NativeByteRange,
  NativeCanonicalKey,
  NativeDesiredAction,
  NativeDesiredFile,
  NativeEvidence,
  NativeEvidenceRole,
  NativeExistingPage,
  NativeGlobalInput,
  NativeGlobalPaths,
  NativeGlobalPhase,
  NativeMergeLogAction,
  NativeMergePlannerAction,
  NativeMergeSequenceTrace,
  NativeMergeStepTrace,
  NativePageCandidate,
  NativePageKind,
  NativePageProposal,
  NativePageType,
  NativeReductionPlan,
  NativeReductionStatus,
  NativeReducerOptions,
  NativeRelatedProposal,
  NativeSourcePage,
  NativeSourceScopedIR,
  NativeStatement,
} from './types';
